#[derive(Debug, PartialEq, Eq)]
pub enum Error {
    NotFound,
    Unimplemented,
    InvalidOffset,
    InvalidFileType,
    InvalidFileName,
    InvalidFileDescriptor,
    InvalidBufferLength,
    InvalidOpenFlags,
    InvalidFdFlags,
    FileAlreadyExists,
    MemoryFileIsNotMounted,
    MemoryFileIsMountedAlready,
    NameTooLong,
    DirectoryNotEmpty,
    ExpectedToRemoveFile,
    ExpectedToRemoveDirectory,
    CannotRemoveOpenedNode,
    CannotRemoveMountedMemoryFile,
    IncompatibleChunkSize,
    InvalidMagicMarker,

    MaxFileSizeExceeded,
    NoSpaceLeftOnDevice,
    OperationNotSupported,
    MetadataUpdateInvalid,
    TooManyOpenFiles,
}
